<?include_once("global.php");?>

<!doctype html>
<html lang="en">
    <?php include_once("./phpComponents/header.php")?>
    
    <style>
        .banner_area .banner_inner .overlay{
            
            background: linear-gradient(0deg, rgba(6, 13, 1, 0.3), rgba(6, 13, 1, 0.3)), url(./img/about.jpg) no-repeat scroll center center;
            background-size:cover
        }
        
        #myBtn {
  display: none;
  position: fixed;
  bottom: 20px;
  right: 30px;
  z-index: 99;
  font-size: 18px;
  border: none;
  outline: none;
  background-color: #2198ce;
  color: white;
  cursor: pointer;
  padding: 15px;
  border-radius: 4px;
}

#myBtn:hover {
  background-color: #555;
}

    </style>
    
    
<body>
    
    <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>

        
	<!--================ Start Header Menu Area =================-->
	<?php include_once("./phpComponents/navbar.php")?>
	
    <!--================ End Header Menu Area =================-->
        
    <!--================ Home Banner Area =================-->
     
    <section class="banner_area">
        <div class="banner_inner d-flex align-items-center">
            <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
            <div class="container" style="opacity: 1;border-radius: 20px;">
                <div class="banner_content text-center">
                    <h2><?translate("Terms and Conditions","&#350;artlar ve ko&#351;ullar")?></h2>
                </div>
            </div>
        </div>
    </section>
    <!--================ End Home Banner Area =================-->

	<!--================ Start About Us Area =================-->
    <!--================ End About Us Area =================-->


    
    <section class="features_causes">
        <div class="container">
     <div class="main_title">
         <br><br>
                <h2>Privacy Policy</h2>
            </div>
            <div class="row">
                <div class="col-lg-12 posts-list">
                    
<p style="text-align:center" align="center"><strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR">ÜYELİK VE DESTEKÇİ SÖZLEŞMESİ</span></strong></p>
<p style="text-align:justify"><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">1.&nbsp;TARAFLAR</span></strong><span style="font-family: &quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><span style="font-family:&quot;Arial&quot;,sans-serif" lang="TR"><span style="mso-spacerun:yes">&nbsp;&nbsp; </span>İşbu Kullanıcı Üye ve Destek Sözleşmesi (Bundan sonra “Sözleşme” olarak anılacaktır.) bir taraftan <strong><span style="font-family:&quot;Arial&quot;,sans-serif;background:white">Esentepe Mah. Talat Paşa Cad. No:5 İç Kapı No:1 Şişli/İstanbul (Kolektif House Levent) adresinde mukim</span></strong>&nbsp;<strong><span style="font-family:&quot;Arial&quot;,sans-serif; background:white">Fikir Bahçıvanı Bilişim Bilgisayar Yazılım Teknolojileri Reklam Danışmanlık Ticaret Limited Şirketi</span></strong>&nbsp;(Bundan sonra&nbsp;<strong><span style="font-family:&quot;Arial&quot;,sans-serif">“Platform Sahibi”</span></strong>&nbsp;olarak anılacaktır.) <span style="mso-spacerun:yes">&nbsp;</span>ile diğer taraftan Platform’da yer alan projeleri incelemek, destekte bulunmak isteyen&nbsp;<strong><span style="font-family:&quot;Arial&quot;,sans-serif">Destekçi</span></strong>&nbsp;ve fikri ürünlerini kamuya yayınlamak suretiyle teşvik ve destek arayan&nbsp;<strong><span style="font-family:&quot;Arial&quot;,sans-serif">Proje Sahibi</span></strong>&nbsp;arasında elektronik ortamda onaylanarak akdedilmiştir.Destekçi ve Proje Sahibi birlikte&nbsp;<strong><span style="font-family:&quot;Arial&quot;,sans-serif">“Kullanıcı”</span></strong>&nbsp;olarak anılacaktır.</span>
</p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">2.&nbsp;TANIMLAR</span></strong><span style="font-family: &quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; background:white" lang="TR">Fikir Bahçıvanı Kitle Fonlama</span></strong><strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"> Platformu </span></strong></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">(“Platform”):</span></strong><span style="font-family: &quot;Arial&quot;,sans-serif;color:black" lang="TR">&nbsp;</span><span lang="TR"><span style="mso-field-code:&quot; HYPERLINK &quot;"><span class="MsoHyperlink"><span style="font-family:&quot;Arial&quot;,sans-serif">“www.fikirbahcivani.com”</span></span>
    </span>
    </span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR">&nbsp;adresli web sitesi, </span><span lang="TR"><span style="mso-field-code:&quot; HYPERLINK &quot;"><span class="MsoHyperlink"><span style="font-family:&quot;Arial&quot;,sans-serif">“fikirbahcivani.com”</span></span>
    </span>
    </span><span class="MsoHyperlink"><span style="font-family:&quot;Arial&quot;,sans-serif; text-decoration:none;text-underline:none" lang="TR"> </span></span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR">adresli mobil web sitesi, mobil uygulama ve ileride Platform Sahibi tarafından belirlenebilecek olan diğer platformlar üzerinden faaliyette bulunan, Destekçi ile Proje Sahiplerini bir araya getiren ve destekçilerin sanal içeriklerini kullanıcıların saksılarında tutan platform,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Destekçi:</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;Platform’da kamunun bilgisine sunulan Projeler’i destekleyen gerçek veya tüzel kişileri,</span><span style="font-size:13.5pt; font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">İçerikler:</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;Projenin anlatımı/tanıtımı için Proje Sahibi tarafından Platform’a yüklenen metin, görsel, video, vs. ile Proje Sahibi ve/veya Destekçi’nin Kullanıcı Profili alanına girdiği bilgiler ve bunlarla sınırlı olmamak üzere, Proje Sahibi ve/veya Destekçi tarafından Platforma giriş yapılan, yüklenen her türlü içeriği,</span><span style="font-size:13.5pt; font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Proje Fonlama Süresi:</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR">&nbsp;Proje Sahibi’nin Platform’a yüklediği Proje kapsamında hedeflenen fonun toplanabilmesi ve Proje Başarı Hedefi’ne ulaşılabilmesi için Proje Sahibi tarafından, ancak Platform’un kendisinin (Fikir Bahçıvanı) fonlanması/desteklenmesi süresiz olmak kaydıyla, minimum 30 (otuz), maksimum 90 (doksan) gün olacak şekilde belirlenen süreyi, </span><span style="font-size:13.5pt;font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Kullanıcı:</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;Platform kapsamındaki hizmetlerden faydalanmak üzere işbu Kullanıcı Üye ve Destekçi Sözleşmesi’ni okuyarak kabul edip, kayıt formunu doldurarak Platform’a üye olan Proje Sahibi veya Destekçi gerçek ve tüzel kişi üyeyi,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Kullanıcı Profili:</span></strong><span style="font-family: &quot;Arial&quot;,sans-serif;color:black" lang="TR">&nbsp;Kullanıcı’nın Platform’a üye olduktan sonra, hazırlamış olduğu ve resim, yazı, bağlantı ve diğer öğelerden oluşan kendisine ait tanıtıcı alanı,</span></p>
<p><strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR">Ödeme Kuruluşu:</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;Sanal pos sistemiyle ödeme almak için Platform Sahibi’in anlaşmalı olduğu firmayı,</span></p>
<p style="text-align:justify"><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Havuz:</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;Destekçilerin desteklemek istedikleri Proje/ler için yaptıkları ödemeleri/fonlamaları ve çeşitli sanal içerikleri, destekçilere satmak koşuluyla destekçilerin saksılarında ve kendi bünyesinde toplayan, Projenin Proje Başarı Hedefi’ne ulaşması veya hedef tutarın %75’ine ulaşması <span style="mso-spacerun:yes">&nbsp;</span>durumunda toplanan tutarı, Platform giderleri için komisyon kesintisini yaparak, Proje Sahibi’ne ileten, Proje’nin Proje Başarı Hedefi’ne veya hedef tutarın %75’ine ulaşamaması durumunda ise toplanan ödemeleri/fonlamaları ve çeşitli sanal içerikleri Destekçilere, göndermiş oldukları içeriklere veya miktarlara göre, aynen saksılarına iade eden Platform Sahibi’ni,</span>
</p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform Sahibi:&nbsp;</span></strong><strong><span style="font-family:&quot;Arial&quot;,sans-serif;background:white;font-weight:normal" lang="TR">Fikir Bahçıvanı Bilişim Bilgisayar Yazılım Teknolojileri Reklam Danışmanlık Ticaret Limited Şirketi</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif" lang="TR">’ni,</span><span style="font-size:13.5pt;font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Proje:&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Kitle fonlaması amacıyla Platform’da erişime açılan her türlü fikri ürün ve hizmeti,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Proje Başarı Hedefi:</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR">&nbsp;Platform kapsamında kitle fonlama süreci başlatan Proje Sahibi’nin, Proje’sini hayata geçirilebilmesi için gerekli olan minimum destek fonu hedefi veya <span style="mso-spacerun:yes">&nbsp;</span>minimum destek fonu hedefinin %75’lik kısmını,</span>
</p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Proje Sahibi:&nbsp;</span></strong><span style="font-family: &quot;Arial&quot;,sans-serif;color:black" lang="TR">Fikri haklarına sahip olduğu Proje’yi, video, metin, fotoğraf, vb. materyallerin yardımıyla anlatarak, onaylanmak üzere, kitle fonlama amacıyla Platform üzerinden Platform Sahibi’ne gönderen, Proje Başarı Hedefi’ne veya %75’lik kısmına ulaşılması halinde Proje’yi hayata geçirmeyi ve Destekçilere Proje kapsamında vadettiği ürün ve/veya hizmetleri sağlamayı taahhüt eden gerçek veya tüzel kişileri,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Fikir Bahçıvanı:</span></strong><span style="font-family: &quot;Arial&quot;,sans-serif;color:black" lang="TR">&nbsp;</span><strong><span style="font-family:&quot;Arial&quot;,sans-serif;background:white;font-weight:normal" lang="TR">Fikir Bahçıvanı Bilişim Bilgisayar Yazılım Teknolojileri Reklam Danışmanlık Ticaret Limited Şirketi</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">’ni,</span><span style="font-size:13.5pt;font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR"></span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Fikir Bahçıvanı Manav:</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR">&nbsp;Platform’un kendi bünyesinde çıkardığı sanal içeriklerin Toprak, Tohum, Su Damlası, Papatya, Gül, Orkide, Yonca, Hayat Suyu İbriği, Yaşam Saksısı, Çiçek Demeti, Budama Makası, Fidan,<span style="mso-spacerun:yes">&nbsp; </span>Tohum Sandığı, El Arabası, Meyve Ağacı, Bahçıvan Ailesi gibi, Platformda çıkan veya Platform dışında anlaşma yapılan ürünlerin üzerinde doğrudan veya dolaylı olarak sahip olduğu veya kontrol ettiği Türkiye’de ve/veya Türkiye dışında faaliyet gösteren pazaryeri aracılığını ifade eder.</span>
</p>
<p style="text-align:justify"><span style="font-size:13.5pt;font-family: &quot;Arial&quot;,sans-serif;color:black" lang="TR">&nbsp;</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">3.&nbsp;AMAÇ VE KONU</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">İşbu Sözleşme, Platform’a üye olan Kullanıcılar’ın, Platform’u kullanırken tabi olduğu kuralları, Proje taahhüdünden ve Projeye destekten doğan hak ve yükümlülükleri tespit eder.</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.&nbsp;KULLANICININ HAK VE YÜKÜMLÜLÜKLERİ</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Kullanıcı,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.1&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">İşbu Sözleşmeyi imzalayabilmek için Türk Medeni Kanunu uyarınca reşit olduğunu, Kullanıcı olabilmek için, Platform Sahibi tarafından üyelikten süresiz yasaklanmış olmadığını, aksi halde işbu Sözleşme’nin Taraflar arasında geçerlilik kazanmayacağını, bu Sözleşme’ye ve Platform’un kural ve ilkelerine uygun hareket edeceğini, Sözleşme’nin tamamını okuduğunu, içeriğini tam olarak anladığını ve tüm hükümlerini kabul edip onayladığını,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.2&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform’un kullanımına veya koşullarına ilişkin olarak sunulan her türlü kural, duyuru ve beyanın işbu Sözleşme’nin ayrılmaz bir parçası olduğunu, Platform Sahibi’nin dilediği zaman,&nbsp;<strong><span style="font-family:&quot;Arial&quot;,sans-serif">işbu Sözleşme’de değişiklik yapabileceğini, Sözleşme koşullarını iptal edebileceğini ve/veya Sözleşme’ye yeni koşullar ekleyebileceğini,</span></strong>&nbsp;yapılan herhangi bir</span><span style="font-size:11.0pt;font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"> </span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR">değişiklikten sonra Platformu kullanmaya devam etmem durumunda, bunun söz konusu değişiklikleri kabul ettiğim anlamına geleceğini bildiğimi,</span><span style="font-size:13.5pt;font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.3&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform Sahibi’nin, kendisi ile Sözleşme akdetmeme ve kendisini herhangi bir sebep göstermeksizin üyeliğe kabul etmeme hak ve yetkisinin olduğunu, Platform Sahibi’nin gerek mevzuattan kaynaklı gerekse tek taraflı tasarrufu sonucu Platform’a veya Kullanıcı Profili alanına İçerik yüklemesine izin vermeme veya üyeliklerini dondurma veya iptal etme hakkına sahip olduğunu,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.4&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform’un kullanımı sırasında mevzuata veya genel ahlak ve adaba aykırı, toplumu veya diğer üyeleri rahatsız edici davranışlarda bulunmasının Platform Sahibi’ne Sözleşme’yi derhal feshetme ve/veya yasal yollara başvurma hakkı verdiğini, bu durumda herhangi bir tazminat talebinde bulunamayacağı gibi kendisinin yüklemiş olduğu her türlü İçerik’i, Platform Sahibi’nin Platform’dan kaldırma ve/veya silme hakkına sahip olduğunu ve Platform Sahibi’nin söz konusu İçerikleri iade yükümlülüğü olmadığını,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.5&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform’a üye olurken dolduracağı kayıt formunda yer alan tüm bilgilerin doğru, eksiksiz, güncel ve hukuka uygun olduğunu ve bu bilgilerin gerekli olduğu durumlarda (şifre unutma gibi), bilginin hatalı ve/veya noksan olmasından doğacak zararlardan dolayı sorumluluğun sadece kendisine ait olacağını, bu hallerde üyeliğinin sona erdirilebileceğini, bu bilgiler arasında yer alan adresinin geçerli tebligat adresi olduğunu, adreste meydana gelebilecek değişikliği Platform Sahibi’ne bildirmediği takdirde bu adrese gönderilen tebligatların usulen geçerli tebligat sonuçlarını doğuracağını,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.6&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform kapsamındaki hizmetlerden yararlanırken Fikir ve Sanat Eserleri Kanunu, Sınai Mülkiyet Kanunu ve yasal düzenlemeler ile hali hazırda yürürlükte olan ilgili her türlü mevzuat hükümleri ve ileride yürürlüğe girecek olan mevzuata, Platform Sahibi’nin yayınlayabileceği Platform kullanım koşulları, ilkeleri dahil tüm bildirimlere uyacağını,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.7&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Kullanıcı Profili alanında, kendi tercihleri doğrultusunda, diğer üyelerin veya henüz üye olmayan fakat Platform’u ziyaret eden kişilerin görmesine ve erişmesine izin vereceği her türlü verinin diğer üyeler veya Platform’u ziyaret eden kişiler tarafından görülebileceğini ve bu nedenle uğrayabileceği zararları bildiğini, bu ayarları tüm risklerini bilerek ve göze alarak yaptığını ve bu nedenle meydana gelebilecek hiçbir zarardan dolayı Platform Sahibi’ni sorumlu tutmayacağını,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.8&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform’un, kendi iradesi doğrultusunda, herhangi bir profili/başlığı/mesajı, projeyi, fotoğrafı, filmi silme, taşıma, kilitleme konusunda yetkili olduğunu ve önceden haber vermeksizin bu yetkiyi kullanabileceğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.9&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform’u kullanmaya başlamış olmakla işbu Sözleşme’yi kabul ederek geçerli bir akdi ilişki içerisine girmeyi zımnen kabul etmiş olduğunu, bu nedenle işbu Sözleşme’nin elektronik ortamda akdedilmiş olduğundan bahisle geçersiz olduğunu ileri sürmeyeceğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.10&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform Sahibi’in yazılı onayı olmadan, işbu Sözleşme’yi veya bu Sözleşme kapsamındaki hak ve yükümlülüklerini, herhangi bir üçüncü kişiye devredemeyeceğini; üyeliğini kendisinden başka kişilerin kullanımına açmayacağını, bu tür devirler veya yetkisiz kullanımlar sonucu kendisinin ve/veya üçüncü kişilerin uğradıkları veya uğrayabilecekleri zararlardan dolayı Platform Sahibi’nin doğrudan ve/veya dolaylı olarak hiçbir şekilde sorumlu tutulamayacağını, tüm sorumluluğun bizatihi kendisine ait olduğunu, üyeliğini başkasına kullandırttığı veya devrettiğinin tespiti halinde üyeliğinin iptal edilebileceğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.11&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform’a yüklediği, mesaj, yorum, sanal hareketler (like, dislike, vb.) de dahil tüm İçerikleri, Platform Sahibi’nin herhangi bir sebep göstermeksizin silebileceğini veya güncelleyebileceğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.12&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Hiçbir şekilde Platform’u ve/veya Platform kapsamındaki İçerikleri referans olarak göstermemeyi, reklam aracı olarak kullanmamayı, Platform’a reklam yüklememeyi ve bu nitelikte olan herhangi bir faaliyette bulunmamayı,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.13&nbsp;</span></strong><strong><span style="font-family: &quot;Arial&quot;,sans-serif;background:white;font-weight:normal" lang="TR">Fikir Bahçıvanı Kitle Fonlama</span></strong><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR"> </span></strong><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black;font-weight:normal" lang="TR">Platformu</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR">’nun isim/marka ve logosunu hiçbir şekilde, hiçbir mecrada kullanmamayı, Platform kapsamında yer alan diğer Projeleri kullanmamayı, kopyalamamayı, çoğaltmamayı, dağıtmamayı, fikri hak ihlalinde bulunmamayı,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.14&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Proje Sahibi sıfatıyla Platform’a yüklediği Proje, 5846 sayılı FSEK uyarınca eser niteliğinde ise, Platform’da yayınlanan Proje’nin eser sahibinin kendisi olduğunu, Proje’den, Proje kapsamındaki eserlerden doğan mali ve manevi hakların münhasıran sahibi olduğunu, işbu Sözleşme’nin FSEK m.52 uyarınca yazılı sözleşme niteliğinde olduğunu, Proje’nin kamu düzeni, genel ahlak ve adaba aykırı olmadığını, kendi isteği ile Proje’nin Platform’da yayınlanmasına, çoğaltılmasına, temsiline, iletimine rıza gösterdiğini, Proje’nin üçüncü kişilerin haklarını ihlal etmediğini, Proje üzerinde üçüncü kişilerin hak iddia etmesi durumunda münhasıran kendisinin sorumlu olduğunu, Platform Sahibi’nin bu yüzden uğrayabileceği her türlü zararı Platform Sahibi’nin ilk talebiyle birlikte derhal tazmin edeceğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.15&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Proje Sahibi sıfatıyla, Platform Sahibi ve Fikir Bahçıvanı Alt Şirketleri’ne, kendisi ile birlikte hareket ederek, Destekçi dahil, başkaca üçüncü şahıslara nazaran öncelik hakkıyla Proje’yi değerlendirme, ürün haline getirme, hayata geçirme hususunda öncelik hak ve yetkisi tanımayı (&nbsp;<em><span style="font-family:&quot;Arial&quot;,sans-serif">örneğin proje konusuna ilişkin hisse devri, ürünü birlikte işleterek kar elde etme hususunu ilk kez bu şirketlere teklif etme gibi&nbsp;</span></em>) ,</span>
</p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.16&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform’a yükleyerek kamunun erişimine sunduğu İçerikler’den bizzat kendisinin sorumlu olduğunu, bunları yayınlamak ve açıklamakla Platform Sahibi tarafından kullanımına (örneğin, düzenleme, değiştirme, çeviri yapma vb. diğer işlemler) izin vermiş olduğunu,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.17&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform Sahibi’nin onay vermesinin akabinde Proje’nin fonlamaya açılmasını takiben, Proje için Proje Fonlama Süresi içerisinde Proje Başarı Hedefine veya hedef tutarın %75’ine <span style="mso-spacerun:yes">&nbsp;</span>ulaşılamaması halinde, Destekçiler’den toplanan miktarın ve/veya sanal içeriklerin Destekçiler’in saksılarına iade edileceğini ve bundan dolayı Proje Sahibi sıfatıyla, Platform Sahibi’nden ve/veya Destekçiler’den ve/veya Ödeme Kuruluşu’ndan herhangi bir talepte bulunamayacağını bildiğini, Platform Sahibi’nin Proje’yi onaylamama ve Platform</span><span style="font-size:13.5pt;font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR"> </span><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">kapsamında fonlamaya açmama hakkının saklı olduğunu, Proje Başarı Hedefi’ne ulaşılması veya hedef tutarın %75’ine ulaşması halinde ise; fonlanan tutarın Ödeme Kuruluşu’nun Platform Sahibi ile olan anlaşması kapsamında, yapacağı kesintiyle kendisine ödeneceğini, komisyon oranına itiraz hakkı bulunmadığını,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.18&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Proje Sahibi sıfatıyla, fonlama için talep etmiş olduğu hedef tutarın veya hedef tutarın %75’inin <span style="mso-spacerun:yes">&nbsp;</span>Proje Fonlama Süresi içerisinde toplanması durumunda; söz konusu Proje için, Platform’da taahhüt ettiği/belirttiği ürün/hizmet konusu edimi ifa edeceğini, toplanan fon miktarına ilişkin Platform kapsamındaki bilgilendirmenin geçerli bilgilendirme olarak kabul edileceğini, Platform’da öngörülen teslim tarihinde taahhüt edilen ürün/hizmetin sunulamamasından ve/veya ifa şeklinden ve zamanından Destekçi’ye karşı tek başına sorumlu olduğunu, teslimatın, masrafları kendisine olmak üzere Destekçi’nin belirttiği adrese yapılacağını, Proje Sahibi’nin taahhüt ettiği ürün veya hizmetin tam veya taahhüt edildiği şekilde adrese sağlanamamasından dolayı Platform Sahibi ve/veya Ödeme Kuruluşu’na herhangi bir talep yöneltilemeyeceğini,</span>
</p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.19&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Destekçi sıfatıyla, Platform’daki Projelere fon sağlamak istediğinde Ödeme Kuruluşu aracılığıyla Platform’da bulunan içerikleri (toprak, tohum, su damlası, papatya, gül, orkide, yonca, çiçek demeti, fidan, ağaç ve benzerleri ile sınırlı kalmamak kaydıyla) satın alıp ödeme yapmayı kabul etmiş sayılacağını, Platform Sahibi’nin işbu Sözleşme konusu hizmet dolayısıyla önden komisyon tahsil etmediğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.20&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Destekçi sıfatıyla, destekte bulunduğu Proje için Platform’da ilgili Proje için belirtilen ürün/hizmet konusu edimin, Proje Fonlama Süresi içerisinde Proje Başarı Hedefi’ne veya hedef tutarın %75’ine ulaşılması durumunda, ifa edileceğini, fon miktarına ilişkin Platform kapsamındaki bilgilendirmenin geçerli bilgilendirme olarak kabul edileceğini, Proje konusu ürün üzerinde Destekçi sıfatıyla fikri mülkiyet dahil, lehine herhangi bir hak ihdas edilemeyeceğini, Proje konusu ürün üzerindeki fikri hakların münhasıran Proje Sahibi’ne ait olduğunu bildiğini, Platform içerisinde yer alan, Proje dahil, herhangi bir İçeriği, Platform Sahibi ve Proje Sahibi’nin yazılı izni olmaksızın, çoğaltıp dağıtmayacağını, yayınlamayacağını, pazarlamayacağını, iletmeyeceğini ve bunlarla sınırlı olmaksızın Platform Sahibi, Proje Sahibi ve diğer üçüncü kişilere ait marka, patent, tasarım, telif veya başkaca mevzuat ile korunan hakları ihlal etmeyeceğini, aksi halde zararın tazmininden tek başına sorumlu olduğunu,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.21&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Destekçi sıfatıyla, Platform’da öngörülen teslim tarihinde taahhüt edilen ürün/hizmetin sunulamaması durumunda; aynen ifa dışında herhangi bir talepte veya tazminat talebinde bulunmayacağını, teslimatın masrafları Proje Sahibi’ne ait olmak üzere, destekte bulunurken bildireceği teslimat adresinin geçerli olacağını, Proje Sahibi’nin taahhüt ettiği ürün ve/veya hizmetin tam veya taahhüt edildiği şekilde adrese sağlanamamasından dolayı, Proje Sahibi dışında, Platform Sahibi ve/veya Ödeme Kuruluşu’na herhangi bir talep yöneltemeyeceğini, Platform’da belirtilen Proje Fonlama Süresi içerisinde, Proje Başarı Hedefi’ne veya hedef tutarın %75’ine<span style="mso-spacerun:yes">&nbsp; </span>ulaşılamaması durumunda, Proje Sahibi’nin Proje’ye ilişkin ürün/hizmeti sunmakla/sağlamakla yükümlü olmayacağını, fonlama kapsamında yapmış olduğu ödemenin veya göndermiş olduğu sanal içeriklerin …</span><span style="font-family:&quot;Arial&quot;,sans-serif; color:red" lang="TR">……..sayfasında yer alan ‘’EĞER PROJE BELİRLENEN HEDEF TUTARA VEYA HEDEF TUTARIN %75 İNE ULŞAMAMASI DURUMUNDA’’ yazısını içeren kısımda, tercih kutularından ‘’ ALMIŞ OLDUĞUM SANAL İÇERİKLER SAKSIMA GERİ GİTSİN’’ seçeneğini işaretlerse </span><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR"><span style="mso-spacerun:yes">&nbsp;</span><span style="mso-spacerun:yes">&nbsp;</span>aynen kendi saksısına iade edileceğini, </span><span style="font-family:&quot;Arial&quot;,sans-serif;color:red" lang="TR">eğer ‘’ALMIŞ OLDUĞUM SANAL İÇERİKLER FİKİR BAHÇVANI PLATFORMUNA DESTEK OLARAK GİTSİN’’ seçeneğini işaretlerse göndermiş olduğu sanal içeriklerin fikir bahçıvanı platformuna gideceğine ve bu sanal içerikler değerince kendisine ödül gönderileceğini kabul etmiş olup</span><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR"> bu kapsamda Proje Sahibi ve Platform Sahibi’nden herhangi bir talepte bulunmayacağını,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.22&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Kullanıcı sıfatıyla, Platform Sahibi’nin işbu Sözleşme’de hiçbir şekilde taraf, garantör, kefil vb. sıfatla yer almadığını, Destekçi’nin ve/veya Proje Sahibi’nin birbirlerine karşı yükümlülüklerini yerine getirmemesi halinde Platform Sahibi’nin üstlenmek zorunda kalabileceği, bunlarla sınırlı olmamak kaydıyla, tazminat, cezai şart, idari para cezası, para cezası vb.’yi, yükümlülüğünü yerine getirmeyen Tarafın, Platform Sahibi’nin ilk talebi üzerine derhal, nakden ve defaten Platform Sahibi’ne ödeyeceğini veya Platform Sahibi’nden bir alacağı mevcutsa (fonlama için herhangi bir bedel toplanmışsa) Platform Sahibi’nin bu bedeli fonlama kapsamında toplanmış olan tutardan mahsup edebileceğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">4.23&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Kullanıcı sıfatıyla, Platform Sahibi’nin, Destekçi ile Proje Sahibi arasındaki hukuki ilişkiden sorumlu olmadığını, işbu Sözleşme’den doğan hak ve alacaklarından dolayı Platform Sahibi’ne herhangi bir talep yöneltemeyeceğini (<em><span style="font-family:&quot;Arial&quot;,sans-serif">projelerin gerçekleşmesinde, proje konusu ürünün teslimatı, proje konusu ürünün oluşturulup oluşturulmaması, desteğin öngörülen hedef fon miktarına</span></em><em><span style="font-family:&quot;Arial&quot;,sans-serif;font-style:normal"> </span></em><i>veya hedef tutarın %75’ine</i> <em><span style="font-family:&quot;Arial&quot;,sans-serif">ulaşması, proje konusu ürünün destekçiye sağlanması gibi destekçi – proje sahibi arasındaki talepler</span></em>&nbsp;), Sözleşme’ye aykırı hareket edilmesi durumunda, öngörülen hedef fon miktarına veya hedef tutarın %75’ine<span style="mso-spacerun:yes">&nbsp; </span>ulaşılsa dahi bunun Proje Sahibi sıfatıyla kendisine Platform Sahibi’nden ve/veya Ödeme Kuruluşu’ndan ödeme vb. yönde talep hakkı vermediğini</span>
</p>
<p style="text-align:justify"><span style="font-size:13.5pt;font-family: &quot;Arial&quot;,sans-serif;color:black" lang="TR">&nbsp;</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">5.&nbsp;PLATFORM SAHİBİNİN HAK ve YÜKÜMLÜLÜKLERİ</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">5.1&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform Sahibi’nin, Platform kapsamında gerçekleştirilebilecek olan değişikleri/güncellemeleri kendisine bildirmeksizin yapma hak ve yetkisine sahip olduğunu,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">5.2&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform Sahibi’nin, Projeleri Platform’a kabul etmeyebileceğini, kabul etmiş olsa dahi herhangi bir zamanda ve herhangi bir sebeple Platform’dan kaldırabileceğini, Proje Sahibi’nin, Proje’sinin fonlamaya sunulmamasından veya kaldırılmasından dolayı Platform Sahibi’nden herhangi bir talepte bulunamayacağını, Platform Sahibi’nin, Destekçi ile Proje Sahibi arasındaki hukuki ilişkiden sorumlu olmadığını, Proje Başarı Hedefi’ne veya hedef tutarın %75’ine ulaşılması halinde dahi, Proje’nin Platform’dan çıkarılmasına karar verebileceğini, böyle bir durumda fonlanan tutarın, yapmış oldukları ödeme / fonlama doğrultusunda, aynen Destekçilerin saksısına iade edileceğini, bu hususun Proje Sahibi’ne herhangi bir talep hakkı vermeyeceğini bildiğini,</span></p>
<p style="text-align:justify"><span style="font-size:13.5pt;font-family: &quot;Arial&quot;,sans-serif;color:black" lang="TR">&nbsp;</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.&nbsp;DİĞER HÜKÜMLER</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.1&nbsp; Fikri Mülkiyet Hakları</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.1.1&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform Sahibi’nin, işbu Sözleşme ile, kendisine herhangi bir lisans, sahibi olduğu patent/faydalı model, endüstriyel tasarım, telif ve markalarının kullanım hakkını veya devrini vermediğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.1.2&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Kullanıcı Profili dahil, Platform’a yüklediği her türlü metin, görsel, video, like- dislike gibi tüm sanal hareketler dahil, İçeriklerin Platform’da yayınlanmasından, çoğaltılmasından bizzat kendisinin sorumlu olduğunu ve Platform Sahibi’ne hiçbir sorumluluk izafe edemeyeceğini, Platform Sahibi’nin Fikir ve Sanat Eserleri yasası uyarınca korsan yazılım, içerik, izinsiz kopyalama, çoğaltma, yayma, umuma iletim dahil mevzuatı ihlal eden her türlü zararlı ve izinsiz İçerikten dolayı zarara uğraması durumunda; zararını, Platform Sahibi’nin ilk talebiyle birlikte, nakden ve aynen derhal tazmin edeceğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.1.3&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Proje Sahibi tarafından Platform’da açıklanan ve duyurusu yapılan Projelerin Fikri ve Sınai Mülkiyet haklarının Proje Sahibi’ne ait olduğunu bildiğini, Proje Sahibi’nin işbu Sözleşme’yi onaylamakla, Platform’da yayınladığı Projeler’in Platform Sahibi tarafından sadece Platform’da değil, kitle fonlama ile ilgili her türlü tanıtım, reklam, pazarlama materyalinde (basılı, görsel mecralarda gösterilmesi, anlatılması, filme alınması, konferans ve sempozyumlarda tanıtılması ve bunlarla sınırlı olmayan diğer alanlarda) çoğaltılmasına, yayınlanmasına, umuma iletimine, temsiline süresiz, münhasıran ve Platform Sahibi’nin üçüncü şahıslara da kullandırmasına yetki tanıyacak şekilde izin verdiğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.1.4&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Proje Sahibi sıfatıyla, işbu Sözleşme ile Platform’a yüklediği Projeler’in daha önceden ülke sınırlaması olmaksızın kitle fonlamaya ilişkin başkaca hiçbir mecrada yayınlanmadığını, bundan sonra da yayınlanmayacağını, aksi halde kendisine aktarılan fon miktarını Platform Sahibi’nin talebi üzerine derhal, aynen ve nakden Ödeme Kuruluş’una iade edeceğini, Ödeme Kuruluşu’nun iade edilen söz konusu tutarı aynen Destekçilere geri ödeyeceğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.1.5&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">İşbu Sözleşme’nin, kendisine, Platform ve/veya Platform içerisinde yer alan İçeriklerle ilgili olarak herhangi bir fikri ve sınai mülkiyet hakkının sahipliğini vermediğini, kendisine, sadece, Platform üzerinde Sözleşme süresi ile sınırlı, münhasır olmayan ve devredilemez bir kullanım hakkı (basit ruhsat) verilmiş olup, Platform’u yalnızca işbu Sözleşme’de belirtilen kapsamda kullanacağımı, bunun dışında başka herhangi bir hak ve lisans verilmediğini, aşağıda sayılanlar dâhil ancak bunlarla sınırlı olmaksızın Platform üzerinde ve/veya Içeriği ile ilgili olarak herhangi bir işlem yapamayacağını,</span></p>
<p style="margin-left:.5in;text-align:justify;text-indent:-.25in;mso-list:l0 level1 lfo1; tab-stops:list .5in"><span style="font-size:10.0pt; mso-bidi-font-size:12.0pt;font-family:Symbol;mso-fareast-font-family:Symbol; mso-bidi-font-family:Symbol;color:black" lang="TR"><span style="mso-list:Ignore">·<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>
    </span><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">a) Platform’u tamamen veya kısmen kopyalama, çoğaltma,</span></p>
<p style="margin-left:.5in;text-align:justify;text-indent:-.25in;mso-list:l0 level1 lfo1; tab-stops:list .5in"><span style="font-size:10.0pt; mso-bidi-font-size:12.0pt;font-family:Symbol;mso-fareast-font-family:Symbol; mso-bidi-font-family:Symbol;color:black" lang="TR"><span style="mso-list:Ignore">·<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>
    </span><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">b) Platform’u tamamen veya kısmen tersinden derleme, tersine mühendislik yapma veya tersine birleştirme,</span></p>
<p style="margin-left:.5in;text-align:justify;text-indent:-.25in;mso-list:l0 level1 lfo1; tab-stops:list .5in"><span style="font-size:10.0pt; mso-bidi-font-size:12.0pt;font-family:Symbol;mso-fareast-font-family:Symbol; mso-bidi-font-family:Symbol;color:black" lang="TR"><span style="mso-list:Ignore">·<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>
    </span><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">c) Platform’u üçüncü taraflara ödünç verme, satma, dağıtma, ifşa etme, pazarlama, kiralama veya aktarma, yararına sunma,</span></p>
<p style="margin-left:.5in;text-align:justify;text-indent:-.25in;mso-list:l0 level1 lfo1; tab-stops:list .5in"><span style="font-size:10.0pt; mso-bidi-font-size:12.0pt;font-family:Symbol;mso-fareast-font-family:Symbol; mso-bidi-font-family:Symbol;color:black" lang="TR"><span style="mso-list:Ignore">·<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>
    </span><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">d) Platform’da yer alan, Platform Sahibi, Fikir Bahçıvanı ve Fikir Bahçıvanı Alt Şirketleri’nin her türlü telif hakkını veya mülkiyet bildirimlerini veya açıklamalarını kaldırma,</span></p>
<p style="margin-left:.5in;text-align:justify;text-indent:-.25in;mso-list:l0 level1 lfo1; tab-stops:list .5in"><span style="font-size:10.0pt; mso-bidi-font-size:12.0pt;font-family:Symbol;mso-fareast-font-family:Symbol; mso-bidi-font-family:Symbol;color:black" lang="TR"><span style="mso-list:Ignore">·<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>
    </span><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">e) Platform’u değiştirme ya da uyarlama,</span></p>
<p style="margin-left:.5in;text-align:justify;text-indent:-.25in;mso-list:l0 level1 lfo1; tab-stops:list .5in"><span style="font-size:10.0pt; mso-bidi-font-size:12.0pt;font-family:Symbol;mso-fareast-font-family:Symbol; mso-bidi-font-family:Symbol;color:black" lang="TR"><span style="mso-list:Ignore">·<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>
    </span><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">f) Platform’u tahsis etme veya alt lisans verme,</span></p>
<p style="margin-left:.5in;text-align:justify;text-indent:-.25in;mso-list:l0 level1 lfo1; tab-stops:list .5in"><span style="font-size:10.0pt; mso-bidi-font-size:12.0pt;font-family:Symbol;mso-fareast-font-family:Symbol; mso-bidi-font-family:Symbol;color:black" lang="TR"><span style="mso-list:Ignore">·<span style="font:7.0pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>
    </span><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">g) Platform’u yukarıdaki lisansa uygun şekilde izin verilenden başka amaçlarla kullanma</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.2&nbsp;Hizmetin Sunulması</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.2.1&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform Sahibi’nin Sözleşme’de sayılan şartlara tamamıyla ya da kısmen uygun olmadığına karar verdiği veya herhangi bir yasal, idari merciinin talebi halinde veya diğer herhangi bir sebeple Platform’da yer alan her türlü İçeriği değiştirme, yayımlamayı reddetme, yayımdan kaldırma hakkı olduğunu bildiğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.2.2&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform Sahibi’nin kendisine bildirimde bulunmak kaydıyla ancak sebep göstermeksizin Platform’u Kullanıcıların erişimine sunmayı sonlandırma hakkı olduğunu bildiğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.3&nbsp;Platform’un Kullanılması</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.3.1&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform’un kullanımına imkan veren tüm bilgilerin kullanım ve yönetiminden bizzat sorumlu olduğunu, kendisine ait cihaz ve hesaplardan gerçekleştirilen her işlemin bizzat tarafınca gerçekleştirilmiş addedileceğini ve bu bilgilerin doğrudan veya dolaylı surette kullanılması, kaybolması veya el değiştirmesi nedeniyle oluşacak tüm zararlardan münhasıran sorumlu olduğunu,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.3.2&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform’u hiçbir şekilde suç teşkil edecek, yasal açıdan takip gerektirecek, ülke çapında ya da uluslararası düzeyde yasaların ve uluslararası anlaşmaların ihlali sonucunu doğuran ya da böyle durumlara teşvik eden, yasadışı, tehditkâr, rahatsız edici, hakaret, küfür veya iftira içeren, küçük düşürücü, kaba, pornografik ya da kamu düzenini bozucu, genel ahlaka aykırı, başkalarını rahatsız ve taciz edecek şekilde, kişilik haklarına zarar verici, yasalara aykırı bir amaç için, başkalarının gizlilik hakkına veya özel hayatına, fikri ve telif haklarına, ticari marka hakları veya başka mülkiyet haklarına tecavüz edecek şekilde kullanmayacağını, Platform ve Platform Sahibi’nin sistemlerinin güvenliğini tehdit edebilecek ve/veya Platform, Platform Sahibi ve/veya diğer kullanıcılara zarar verebilecek eylemlerde bulunmayacağımı, Platform’a virüs veya başka zararlı unsurlar içeren hiçbir tür İçerik, yazılım ya da başka herhangi bir malzeme yüklemeyeceğini ve Platform’un çalışmasını veya diğer kullanıcıların Platform’dan faydalanmasını engelleyebilecek herhangi bir girişimde bulunmayacağını, ayrıca Platform Sahibi’nin altyapısı üzerine makul olmayan veya orantısız büyüklükte yük getiren veya bir virüs veya başkaca bir zararlı unsur içeren herhangi bir işlem yapmayacağımı, Platform’un kaynak kodlarına veya Platform Sahibi’nin sistemlerine yetkisiz bir şekilde erişmeyeceğini, bu bilgileri ve içerikleri kopyalamayacağını, silmeyeceğini, değiştirmeyeceğini ya da bu yönde denemeler yapmayacağını; Platform’un çalışmasını engelleyecek yazılımlar kullanmayacağını, kullanmaya çalışması veya her türlü yazılım, donanım ve sunucuların çalışmasını aksatması, bozulmasına yol açması, tersine mühendislik yapması, saldırılar düzenlemesi, meşgul etmesi veya bunlara sair surette müdahale etmesinin, Platform Sahibi’nin sunucularına erişim sağlamaya çalışmasının kesinlikle yasak olduğunu, yukarıda anılan yöntemlerle yahut sair şekillerde Platform Sahibi veya Platform ile rekabet etmeyeceğini, bu amaçla hareket eden üçüncü taraflara destek vermeyeceğini, aksi halde tek sorumlu ve muhatabın kendisi olduğunu, Platform Sahibi’nin yukarıda sıralanan aykırı eylemleri sebebiyle karşılaşacağı her türlü zarar ve ziyanı, hak sahiplerine veya üçüncü kişilere ödenmek zorunda kalınacak bedel, tazminat, adli/idari para cezaları vesair ve sarf edilecek masraflar ile birlikte Platform Sahibi’nin ilk talebi üzerine derhal tazmin etmekle yükümlü olduğunu, Platform Sahibi’nin uğradığı ve/veya karşılamak zorunda kalacağı her türlü zarar ve ziyanın tarafına rücu edileceğini bildiğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.3.3&nbsp;Sorumluluğun Sınırlandırılması: </span></strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR">Platform’a girilmesi, Platform’un ya da Platform’daki bilgilerin, İçeriklerin ve diğer verilerin kullanılması, hizmetlerden yararlanılması, Platform vasıtasıyla İçerik paylaşılması yahut Platform’da paylaşılan İçerikler sebebiyle, Sözleşme’nin ihlali, haksız fiil ya da başkaca sebeplere binaen, ağır kusuru dışında doğabilecek doğrudan ya da dolaylı hiçbir zarardan Platform Sahibi’nin sorumlu olmadığını; Platform Sahibi’nin, Sözleşme’nin ihlali, haksız fiil, ihmal veya diğer sebepler neticesinde; hata, ihmal, verilerin silinmesi, kaybı, işlemin veya iletişimin gecikmesi, bilgisayar virüsü, iletişim hatası, hırsızlık, imha, izinsiz olarak kayıtlara girilmesi, kayıtların değiştirilmesi veya kullanılması hususunda herhangi bir sorumluluk kabul etmediğini; Platform’a ya da listelenen, link verilen sitelere girilmesi, Platform’un kullanılması ile Platform’u ziyaret etmem sonucunda doğabilecek her tür sorumluluktan, avukatlık ücreti dahil mahkeme masrafları ve diğer masraflar da dahil olmak üzere Platform Sahibi’nin her tür zarar ve talep hakkından beri kılındığını,</span><span style="font-size:13.5pt;font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.3.4&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;PLATFORM’U KULLANMASI, PLATFORM KAPSAMINDAKİ HİZMETLERDEN YARARLANMASI, PLATFORM KAPSAMINDAKİ VE/VEYA PLATFORM VASITASIYLA PAYLAŞILAN İÇERİKLERDEN FAYDALANMASI İLE İLGİLİ HER TÜRLÜ RİSKİN VE BUNA İLİŞKİN SORUMLULUĞUN MÜNHASIRAN TARAFINA AİT OLACAĞINI, PLATFORM’UN KULLANIMINA İLİŞKİN OLARAK PLATFORM SAHİBİ’NDEN HANGİ NAM ALTINDA OLURSA OLSUN HERHANGİ BİR ŞEKİLDE TALEPTE BULUNMAYACAĞINI, PLATFORM SAHİBİ’NİN, TEDARİKÇİLERİNİN, DAĞITICILARININ VE ÜRETİCİLERİN PLATFORM’A VE PLATFORM KAPSAMINDAKİ İÇERİKLERE, FONKSİYONLARA, GÜVENİRLİĞİNE, UYGUNLUĞUNA, İHTİYAÇLARI KARŞILAMA YETERLİLİĞİNE İLİŞKİN HERHANGİ BİR GARANTİ YA DA TAAHHÜT VERMEDİĞİNİ, PLATFORM SAHİBİ’NİN, UYGULANACAK HUKUKUN IZIN VERDIĞI ÖLÇÜDE, KAR KAYBI, ŞEREFIYE VE İTİBAR KAYBI DAHİL ANCAK BUNLARLA SINIRLI OLMAKSIZIN PLATFORM’UN KULLANIMI, İÇERİK PAYLAŞIMI YAHUT SATIN ALMA FAALİYETLERİ NETİCESİNDE YAHUT KULLANICI FİİLLERİ NEDENİYLE MEYDANA GELEN HİÇBİR DOĞRUDAN, DOLAYLI, ÖZEL, ARIZI, CEZAİ ZARARDAN SORUMLU OLMAYACAĞINI, PLATFORM ÜZERİNDEN İÇERİKLERİN “OLDUĞU GİBİ” SUNULMAKTA OLUP BU KAPSAMDA PLATFORM SAHİBİ’NİN BUNLARIN DOĞRULUĞU, TAMLIĞI VE GÜVENİLİRLİĞİ İLE İLGİLİ HERHANGİ BİR SORUMLULUK YA DA TAAHHÜDÜ BULUNMADIĞINI,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.3.5&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;Platform üzerinden Platform Sahibi’nin kontrolünde olmayan başka internet sitelerine ve/veya platformlara, dosyalara veya içeriklere link verilebileceğini, üçüncü taraflara ait hizmetlerin sunulabileceği ve bu tür linklerin yöneldiği internet sitesini veya işleten/hizmeti veren kişiyi desteklemek amacıyla veya internet sitesi veya içerdiği bilgilere yönelik herhangi bir türde bir beyan veya garanti niteliği taşımadığını, söz konusu linkler vasıtasıyla erişilen platformlar, internet siteleri, dosyalar ve içerikler, hizmetler veya ürünler veya bunların içeriği hakkında Platform Sahibi’nin herhangi bir sorumluluğu olmadığını,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.3.6&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;Platform üzerinden sunulan İçeriklere erişim ve bunların kalitesinin büyük ölçüde ilgili internet servis sağlayıcısından temin edilen hizmetin kalitesine dayandığını ve söz konusu hizmet kalitesinden kaynaklı sorunlarda Platform Sahibi’nin herhangi bir sorumluluğunun bulunmadığını, Platform’un işleyişinin kusurdan ari olmadığını ve zaman zaman teknik aksaklıklar veya erişim engelleriyle karşılaşabileceğini bildiğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.3.7&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;Platform’un kullanımı ile ilgili olarak cep telefonu, tablet, bilgisayar veya diğer cihazlarda oluşabilecek her türlü hasar ve bu sayılanlarla sınırlı olmamak üzere her türlü zarar ve sorumluluğun tarafına ait olduğunu, Platform’un kullanımı halinde meydana gelecek hiçbir olay nedeni ile Platform Sahibi’nin sorumlu tutmayacağını,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.3.8&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;Platform Sahibi, Fikir Bahçıvanı Alt Şirketleri, ortakları, ve/veya bağlı kuruluşlarının, Platform’u kullanmam sebebiyle uğrayabileceği kar, gelir, veri kaybından veya diğer mali kayıplardan veya sonuçta meydana gelen özel ve/veya dolaylı hasarlardan, idari/adli para cezalarından ve/veya maddi/manevi zararlardan, mevzuatta aksi belirtilmediği sürece, yükümlü olmayacağını bildiğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.4&nbsp; Kişisel Verilerin Korunması</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.4.1&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;Platform Sahibi’nin kişisel verilerin korunmasına ilişkin mevzuat hükümleri çerçevesinde, Kullanıcıların kişisel verilerinin güvenli şekilde muhafazasını ve hukuka uygun olarak işlenmesini sağlamak için teknolojik ve alt yapısal imkanlarını kullanarak, gerekli tüm teknik ve idari tedbirleri alacağını,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.4.2&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;Platform aracılığıyla ya da Platform ile bağlantılı olarak sağlanan ya da toplanan kişisel bilgilerinin,&nbsp;</span><span lang="TR"><a href="https://www.fikirbahcivani.com./gizlilik"><span style="font-family:&quot;Arial&quot;,sans-serif">https://www.fikirbahcivani.com./gizlilik</span></a>
    </span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR">adresinde yer alan Fikir Bahçıvanı Gizlilik Politikası ve&nbsp;</span><span lang="TR"><a href="https://www.fikirbahcivani.com/kayit"><span style="font-family:&quot;Arial&quot;,sans-serif">https://www.fikirbahcivani.com/kayit</span></a>
    </span><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR">&nbsp;adresinde yer alan Fikir Bahçıvanı Gizlilik Politikası kapsamında toplanacağını ve Fikir Bahçıvanı Gizlilik Politikası ve Platform’a kayıt esnasındaki Gizlilik Politikası’na uygun olarak işlenebileceğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.4.3 </span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Fikir Bahçıvanı Gizlilik Politikası ve Platform’a kayıt esnasındaki Gizlilik Politikası’nı inceleyerek, Platform Sahibi tarafından veri sorumlusu sıfatıyla işlenebilecek kişisel verilerin işlenme amaçları, aktarılabileceği kişiler, toplanma yöntemi ve hukuki sebebi ile söz konusu kişisel verilere ilişkin hakları hakkında detaylı bilgi edinebileceğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.4.4&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;Kişisel verilerinin, Fikir Bahçıvanı Gizlilik Politikası, Platform’a kayıt esnasındaki Gizlilik Politikası ve/veya bu Sözleşme’de belirtilen amaçlarla, proje sahipleri, kullanıcılar, Fikir Bahçıvanı alt şirketleri ve işbirliği yapılan veya hizmet alınan ya da doğrudan hizmet sunan iş ortakları, tedarikçi firmalar ile bankalar, ödeme kuruluşları, finans kuruluşları ile sair gerçek veya tüzel kişiler ve Platform Sahibi’nin Sözleşme kapsamındaki hak ve yükümlülüklerini devredebileceği yurt içinde veya yurt dışındaki üçüncü kişi veya kuruluşa veya alt şirketine ilgili mevzuata uygun olarak aktarılabileceğini bildiğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.4.5 </span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform Sahibi’nin, Sözleşme kapsamındaki hak ve yükümlülüklerini devredebileceğini ve kişisel verileri ilgili mevzuata uygun olarak yurt içinde veya yurt dışında üçüncü kişi veya kuruluşa veya alt şirketine aktarabileceğini bildiğimi; kişisel verilerin Platform Sahibi’nin sunucularında, mevzuata uygun olarak ve bu çerçevede belirlenmiş kurallar ile korunacağını, saklanacağını; 5651 sayılı Kanun gereği Kullanıcıların trafik verilerinin ve yürürlükte olan veya ileride yürürlüğe girecek olan diğer mevzuat ile tutulması gereken tüm verilerin tutulacağını ve ilgili mevzuat gereği aktarım yapılması gereken kurum ve kuruluşlara iletileceğini bildiğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.5&nbsp; Mücbir Sebep</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">Platform Sahibi’nin, üstlendiği yükümlülükleri, kısmen veya tamamen, geçici veya daimi olarak durduracak ve/veya imkansız kılacak şekilde ve derecede meydana gelen doğal afetler, harp, seferberlik, yangın halleri, hükümet ve idari makam kararları ve benzeri hallerin mücbir sebep sayılacağını, bu gibi durumlar karşısında Platform Sahibi’nin yükümlülüklerini yerine getirmemesi sebebiyle kendisine karşı sorumlu olmayacağını,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.6&nbsp; Uyuşmazlıkların Çözümü ve Kayıtların Geçerliliği</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif;color:black" lang="TR"></span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.6.1&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;Platform Sahibi ile arasında, işbu Sözleşme'den kaynaklanan her türlü anlaşmazlıkların çözümünde Türk Hukukunun uygulanacağını, münhasıran İstanbul Avrupa Mahkemeleri ve İcra Daireleri’nin yetkili olacağını bildiğini,</span></p>
<p style="text-align:justify"><strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">6.6.2&nbsp;</span></strong><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">&nbsp;İşbu Sözleşme’den doğabilecek ihtilaflarda, Platform Sahibi’nin kendi veritabanında, sunucularında tuttuğu elektronik ve sistem kayıtlarının, ticari kayıtlarının, defter kayıtlarının, mikrofilm, mikrofiş ve bilgisayar kayıtlarının muteber bağlayıcı, kesin ve münhasır delil teşkil edeceğini ve bu maddenin HMK 193. madde anlamında delil sözleşmesi niteliğinde olduğunu,</span></p>
<p style="text-align:justify"><span style="font-family:&quot;Arial&quot;,sans-serif; color:black" lang="TR">kabul, beyan ve taahhüt eder.</span></p>
<p style="text-align:justify"><span style="font-size:13.5pt;font-family: &quot;Arial&quot;,sans-serif;color:black" lang="TR">&nbsp;</span></p>
<p class="MsoNormal" style="text-align:justify"><span lang="TR">&nbsp;</span></p>
                    
                    
				</div>
				
				
				
			
                    
			</div>
        </div>
    </section>
    <!--================End Team Area =================-->

	<!--================ Start CTA Area =================-->
	
	<!--================ Start CTA Area =================-->
	<?php if($logged==0)include_once("./phpComponents/volunteer.php")?>
	<!--================ End CTA Area =================-->

	<!--================ Start footer Area  =================-->	
     <?php include_once("./phpComponents/footer.php")?>
    <!--================ End footer Area  =================-->  
        
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="js/jquery-3.2.1.min.js"></script>
        <script src="js/popper.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/stellar.js"></script>
        <script src="vendors/lightbox/simpleLightbox.min.js"></script>
        <script src="vendors/nice-select/js/jquery.nice-select.min.js"></script>
        <script src="js/jquery.ajaxchimp.min.js"></script>
        <script src="js/mail-script.js"></script>
        <!-- contact js -->
        <script src="js/jquery.form.js"></script>
        <script src="js/jquery.validate.min.js"></script>
        <script src="js/contact.js"></script>
        <!--gmaps Js-->
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
        <script src="js/gmaps.min.js"></script>
        <script src="js/theme.js"></script>
        
        <script>
// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    document.getElementById("myBtn").style.display = "block";
  } else {
    document.getElementById("myBtn").style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  const scrollToTop = () => {
  const c = document.documentElement.scrollTop || document.body.scrollTop;
  if (c > 0) {
    window.requestAnimationFrame(scrollToTop);
    window.scrollTo(0, c - c / 18);
  }
};
scrollToTop();
}
</script>

    </body>
</html>